import bruxelles from "../assets/images/bruxelles.png";
import bruxelles2 from "../assets/images/bruxelles2.png";
import ilemaurice from "../assets/images/ilemaurice.png";
import mauricelille from "../assets/images/mauricelille.png";
import arizona from "../assets/images/arizona.png";
import arizona2 from "../assets/images/arizona2.png";
import ecuador from "../assets/images/ecuador.png";
import ecuador2 from "../assets/images/ecuador2.png";
import cuba from "../assets/images/cuba.png";
import cuba2 from "../assets/images/cuba2.png";
import madrid from "../assets/images/madrid.png";
import madrid2 from "../assets/images/madrid2.png";
import rome from "../assets/images/rome.png";
import rome2 from "../assets/images/rome2.png";
import hawai from "../assets/images/hawaii.png";
import hawai2 from "../assets/images/hawaii2.png";
import hongkong from "../assets/images/hongkong.png";
import hongkong2 from "../assets/images/hongkong2.png";
import lecap from "../assets/images/lecap.png";
import lecap2 from "../assets/images/lecap2.png";
import capdagde from "../assets/images/capdagde.png";
import capdagde2 from "../assets/images/capdagde2.png";
import reykjavik from "../assets/images/reykjavik.png";
import reykjavik2 from "../assets/images/reykjavik2.png";
import marrakech from "../assets/images/marrakech.png";
import marrakech2 from "../assets/images/marrakech2.png";

const Destinations = [
  {
    id: 1,
    name: "Bruxelles",
    description:
      "La commune de Bruxelles proprement dite est constituée de plusieurs territoires : d'abord le Pentagone qui délimite le centre historique, ensuite les anciennes communes de Laeken, Haren et Neder-Over-Heembeek, et enfin les parties de communes voisines annexées qui sont le quartier Nord-Est avec l'extension moderniste du quartier nord et ses immeubles tours, le « quartier européen » (partie informelle du quartier Léopold) et le quartier de l'avenue Louise ainsi que le bois de la Cambre et une partie de la forêt de Soignes. La ville de Bruxelles s'étend sur 32,61 km² et compte 185 053 habitants au 1er septembre 2019, 94 863 hommes et 90 190 femmes, soit une densité de 5 510,21 habitants/km².",
    pic1: bruxelles,
    pic2: bruxelles2,
    key: [
      "Salé",
      "Transport",
      "Frais",
      "Bière",
      "PMU",
      "SPA",
      "Marcher",
      "Whisky",
      "Lève Tôt",
      "Danser toute la nuit",
      "Repos",
      "Boeuf",
      "Chocolat",
      "Payer plein pot",
      "Calme",
      "nuit",
      "Expression",
      "Frites",
      "Tropico",
    ],
  },
  {
    id: 2,
    name: "Ile Maurice",
    description:
      "Morbi a metus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Nullam sapien sem, ornare ac, nonummy non, lobortis a, enim. Nunc tincidunt ante vitae massa. Duis ante orci, molestie vitae, vehicula venenatis, tincidunt ac, pede. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Etiam commodo dui eget wisi. Donec iaculis gravida nulla. Donec quis nibh at felis congue",
    pic1: ilemaurice,
    pic2: mauricelille,
    key: [
      "Maillot",
      "Farniente",
      "Plage",
      "Etoilé",
      "Randonnée",
      "Sunset",
      "Spa",
      "Hamac",
      "Marcher",
      "Rhum",
      "Lève tard",
      "Danser toute la nuit",
      "Paysages",
      "Repos",
      "Poisson",
      "Nature",
      "Payer plein pot",
      "Calme",
      "Tropique",
    ],
  },
  {
    id: 3,
    name: "Arizona",
    description:
      "L'Arizona est un État de l'Ouest des États-Unis. Sa capitale et plus grande ville est Phoenix. Avec une superficie de 295 254 km², il est le sixième État américain le plus vaste, et le seizième plus peuplé avec 7 151 502 habitants en 2020. Bordé par la Californie, le Nevada, l'Utah, le Nouveau-Mexique et les États mexicains de la Basse-Californie et du Sonora au sud, l'Arizona est l'un des quatre États des Four Corners. Il fait en outre partie de la Sun Belt (« ceinture du soleil ») qui connaît une forte croissance démographique en raison de l'héliotropisme. Situé au sud des montagnes Rocheuses, l'Arizona est un des États des montagnes. Traversé par le fleuve Colorado, l'État comprend de spectaculaires formations géologiques, telles que le Grand Canyon, Meteor Crater et Monument Valley. Le territoire est sous souveraineté espagnole à partir du xvie siècle, en tant que région de la Nouvelle-Espagne. Le Mexique en prend possession en 1821 lors de son indépendance : il devient une partie de la Haute-Californie. En 1848, à l'issue de la guerre américano-mexicaine, les États-Unis annexent l'Arizona, puis agrandissent son territoire en 1853 lors de l'achat Gadsden. Il adhère tardivement à l'Union, le 14 février 1912, et en devient le 48e État. Il est divisé en quinze comtés, et près du quart de son territoire est constitué par vingt-et-une réserves indiennes. Les Navajos et d'autres peuples Apaches y sont majoritaires.",
    pic1: arizona,
    pic2: arizona2,
    key: [
      "Sucré",
      "Voiture",
      "Farniente",
      "Burger",
      "PMU",
      "Randonnée",
      "whisky",
      "Lève tard",
      "Paysages",
      "Désert",
      "Boeuf",
      "Fromage",
      "Payer plein pot",
      "Tempête",
      "Expression",
      "Frites",
      "Tropico",
    ],
  },
  {
    id: 4,
    name: "Equateur",
    description:
      "L’Équateur, en forme longue la république d'Équateur ou république de l'Équateur (en espagnol : Ecuador et República del Ecuador), est un pays d'Amérique du Sud, frontalier du Pérou au sud et à l'est et de la Colombie au nord-est, baigné à l'ouest par l'océan Pacifique. L'Équateur, avec une superficie de 283 520 km², est l'un des plus petits d'Amérique du Sud aux côtés de Suriname, de l'Uruguay, de Guyana et du Paraguay.Le pays est partagé en trois grandes régions géographiques : la côte du Pacifique, où se trouve le grand port de Guayaquil qui est en même temps la plus grande ville du pays, la partie andine du pays, où se trouve la capitale Quito, et l'Amazonie équatorienne, dans l'est du pays. Les deux premières de ces régions concentrent l'essentiel de la population et des activités économiques du pays, tandis que la partie amazonienne, moins peuplée, recèle des ressources significatives en hydrocarbures, ainsi qu'une biodiversité extrêmement importante. À ces trois grandes régions continentales s'ajoute une région insulaire formée par les îles Galápagos; celles-ci forment un archipel situé dans le Sud-Est de l'océan Pacifique sud, à un millier de kilomètres à l'ouest de la côte équatorienne.",
    pic1: ecuador,
    pic2: ecuador2,
    key: [
      "Café",
      "Farniente",
      "Randonnée",
      "Hamac",
      "Aller au marché",
      "Rhum",
      "Lève tard",
      "Danser",
      "Paysage",
      "Aventure",
      "Forêt tropicale",
      "Flûte de pan",
      "Poisson",
      "Chocolat",
      "Négocier",
      "Expression",
      "Tropique",
    ],
  },
  {
    id: 5,
    name: "Cuba",
    description:
      "Cuba, en forme longue la république de Cuba (en espagnol : República de Cuba), est un État insulaire des Caraïbes formé de l'île de Cuba (la plus grande île des Antilles), de l'île de la Jeunesse (appelée île aux Pins jusqu'en 1978) et de 4 095 cayes et îlots. Il est situé à l'ouest des grandes Antilles, à la confluence de la mer des Caraïbes, du golfe du Mexique et de l'océan Atlantique ; au nord-est des Îles Caïmans ; au nord-nord-ouest de la Jamaïque ; à l'est du Mexique (Yucatán) ; au sud-sud-est de la péninsule de Floride ; au sud-ouest des Bahamas ; à l'ouest d'Haïti et des îles Turques-et-Caïques. Première île des Caraïbes en termes de superficie, devançant Hispaniola (qui abrite deux pays : Haïti et la République dominicaine), l'île de Cuba est toutefois derrière en nombre d'habitants avec près de 11 253 000 habitants. Sa capitale est La Havane, sa langue officielle l'espagnol et sa devise le peso cubain. L'île a été une colonie espagnole de 1492 à 1898 puis un territoire des États-Unis jusqu'au 20 mai 1902. Depuis la révolution cubaine de 1959, le pays se définit comme une république socialiste, bien que Fidel Castro n'officialise le caractère socialiste du régime que le 17 août 1961, à la suite de l'épisode de la baie des Cochons, dont le Parti communiste de Cuba, créé en 1965, constitue la « force dirigeante supérieure » et, de fait, le parti unique. Le régime est souvent qualifié de dictature.",
    pic1: cuba,
    pic2: cuba2,
    key: [
      "Café",
      "Voiture",
      "Maillot",
      "Farniente",
      "Spa",
      "Hamac",
      "Aller au marché",
      "Rhum",
      "Lève tard",
      "Danser",
      "Paysage",
      "Aventure",
      "Poisson",
      "Négocier",
      "Oppression",
      "Tropique",
    ],
  },
  {
    id: 6,
    name: "Madrid",
    description:
      "Madrid est la capitale et la plus grande ville d'Espagne. Située dans la partie centrale du royaume, elle est également la capitale et la ville la plus peuplée de la Communauté de Madrid. En tant que capitale d'État, elle abrite la plupart des institutions politiques du pays, dont la résidence royale, le siège du gouvernement et le Parlement. Elle compte une population d'environ 3,3 millions d'habitants intra-muros sur une superficie totale de 604,3 km², au sein d'une aire urbaine d'environ 6,5 millions d'habitants en 2014. En comptant sa population intra-muros, Madrid est la deuxième ville de l'Union européenne, derrière Berlin. Ville mondiale, elle abrite le siège de nombreuses institutions, dont l'Organisation mondiale du tourisme, l'Organisation des États ibéro-américains, l'Académie royale espagnole et l'Institut Cervantes. Considérée comme l'une des principales places financières de l'Europe du Sud, elle partage le statut de cœur économique de l'Espagne avec Barcelone. Elle accueille le siège social des plus grandes entreprises du pays, comme Telefónica, Repsol ou Iberia. Les bâtiments d'architecture récente côtoient des constructions de style néo-classique, telles que la porte d'Alcalá, la place de Cybèle ou la Cathédrale de l'Almudena. Ville d'art, ses trois principaux musées, le musée du Prado, le musée Reina Sofía et le musée Thyssen-Bornemisza, comptent parmi les plus visités au monde3. En outre, Madrid abrite deux des plus grands clubs de football au monde, le Real Madrid et l'Atlético de Madrid.",
    pic1: madrid,
    pic2: madrid2,
    key: [
      "Salé",
      "Vin",
      "Musée",
      "Spa",
      "Whisky",
      "Lève tôt",
      "Danser",
      "Guitare",
      "Boeuf",
      "Peinture",
      "Fromage",
      "Payer",
      "Calme",
      "Expression",
      "Potatoes",
      "Tropico",
    ],
  },
  {
    id: 7,
    name: "Rome",
    description:
      "Rome est la capitale de l'Italie. Située au centre-ouest de la péninsule italienne, près de la mer Tyrrhénienne, elle est également la capitale de la région du Latium. En 2019, elle compte 2 844 395 habitants établis sur 1 285 km², ce qui fait d'elle la commune la plus peuplée d'Italie et la troisième plus étendue d'Europe après Moscou et Londres. Son aire urbaine recense 4 356 403 habitants en 2016. Elle présente en outre la particularité de contenir un État enclavé dans son territoire : la cité-État du Vatican (Stato della Città del Vaticano), dont le pape est le souverain. C'est le seul exemple existant d'un État à l'intérieur d'une ville. L'histoire de Rome s'étend sur plus de vingt-huit siècles, depuis sa fondation mythique par Romulus en 753 av. J.-C. jusqu'à son rôle actuel de capitale de la république italienne. Second berceau de la civilisation occidentale après Athènes, la ville fut successivement le centre de la monarchie romaine, de la République romaine (509 av. J.-C. – 27 av. J.-C.), puis de l'Empire romain (27 av. J.-C. – 330). Durant cette période, où naît la célèbre expression proverbiale « tous les chemins mènent à Rome », la ville aurait compté entre un et deux millions d'habitants et domine l'Europe, l'Afrique du Nord et le Moyen-Orient tant militairement que culturellement, diffusant dans ces territoires la langue latine, ses arts et techniques ainsi que la religion chrétienne. Depuis le Ier siècle elle abrite le siège de l'Église catholique romaine, au sein des États pontificaux (752-1870) puis de la Cité du Vatican. Sa devise antique, Senatus populusque Romanus (le Sénat et le peuple de Rome) abrégée en S.P.Q.R., a traversé les siècles et reste de nos jours l'emblème de la ville.",
    pic1: rome,
    pic2: rome2,
    key: [
      "Salé",
      "Pizza",
      "Vin",
      "Musée",
      "Spa",
      "Whisky",
      "Lève tôt",
      "Danser",
      "Paysage",
      "Boeuf",
      "Peinture",
      "Fromage",
      "Calme",
      "Expression",
      "Potatoes",
      "Tropico",
    ],
  },
  {
    id: 8,
    name: "Hawaï",
    description:
      "Hawaï ou Hawaii est un État des États-Unis. Constitué d'un archipel de 137 îles, il s'agit du seul État américain situé en dehors du continent nord-américain, puisqu'il est situé en Océanie, et de l'un des deux États américains non contigus, avec l'Alaska. Les huit principales îles sont Niihau, Kauai, Molokai, Lanai, Kahoolawe, Maui, l'île d'Hawaï et Oahu, où se trouve la capitale Honolulu. L'archipel fait partie de la Polynésie et se situe dans le centre de l'océan Pacifique nord, à 3 718 km au sud de la péninsule d'Alaska, à 3 792 km à l'ouest-sud-ouest de Punta Gorda, sur la côte californienne, et à 5 713 km à l'est de l'île de Hokkaidō au Japon. En outre, il est le 50ème et dernier État à avoir été admis dans l'Union, le 21 août 1959. La variété de ses paysages, marqués notamment par un volcanisme très actif (Hualālai, Kīlauea, Mauna Kea, Mauna Loa), un climat tropical humide et un patrimoine naturel endémique, en font une destination prisée aussi bien des touristes que des scientifiques. De plus, on peut observer les animaux de la mer, en bateau ou lors de plongée sous-marine.",
    pic1: hawai,
    pic2: hawai2,
    key: [
      "Sucré",
      "Maillot",
      "Farniente",
      "Burger",
      "Montagne",
      "Spa",
      "Sport",
      "Aller au marché",
      "Rhum",
      "Lève tôt",
      "Danser",
      "Paysage",
      "Forêt",
      "Poisson",
      "Nature",
      "Tempête",
      "Tropique",
    ],
  },
  {
    id: 9,
    name: "Hong-Kong",
    description:
      "Hong Kong (litt. « port aux parfums » ou « port parfumé »), officiellement la région administrative spéciale de Hong Kong de la république populaire de Chine, est la plus grande et la plus peuplée des deux régions administratives spéciales (RAS) de la république populaire de Chine, l'autre étant Macao. Au sein de la mégalopole du delta de la Rivière des Perles, elle compte environ sept millions d'habitants que l'on appelle Hongkongais dont l'espérance de vie, de 84,2 ans, est la plus longue au monde en 2017. Hong Kong est située dans le Sud-Est de la Chine, sur la rive orientale de la Rivière des Perles, dans le delta du même nom. Cette région administrative, qui occupe une péninsule sur la côte sud ainsi que quelques îles, est baignée par la mer de Chine méridionale. Elle jouxte la province du Guangdong au nord. Hong Kong est la huitième entité commerciale mondiale5. En 2016, son économie est considérée comme la plus libérale au monde depuis 1995 selon la fondation américaine « Heritage Foundation ». En 2019, Hong Kong est la 3ème place financière au monde après New York et Londres, cette trilogie est d'ailleurs appelée par certains médias anglophones « Nylonkong ». En 2022, Hong Kong est classée en 14e position pour l'indice mondial de l'innovation.",
    pic1: hongkong,
    pic2: hongkong2,
    key: [
      "Thé",
      "Transport",
      "SPA",
      "Whisky",
      "Lève tôt",
      "Poisson",
      "Payer",
      "Oppression",
      "Tropico",
    ],
  },
  {
    id: 10,
    name: "Le Cap",
    description:
      "Le Cap est une ville d'Afrique du Sud, capitale de la colonie du Cap (1652-1910) puis de la province du Cap (1910-1994). Elle est actuellement la capitale provinciale du Cap-Occidental. Depuis 1910, Le Cap est également la capitale parlementaire du pays aux côtés de Pretoria (capitale administrative) et de Bloemfontein (capitale judiciaire). La ville du Cap, fondée en 1652, est considérée comme la cité-mère d'Afrique du Sud. Ville la plus australe du continent africain, elle est établie sur les rives de la baie de la Table et est surmontée par la montagne de la Table coiffée de deux pics nommés Lion's Head et Devil's Peak. La ville a été baptisée en référence au cap de Bonne-Espérance, découvert par le Royaume de Portugal, situé à plus de 47 km au sud de son centre historique.",
    pic1: lecap,
    pic2: lecap2,
    key: [
      "Randonnée",
      "SPA",
      "Sport",
      "Aller au marché",
      "Rhum",
      "Lève tôt",
      "Danser",
      "Paysage",
      "Aventure",
      "Expression",
      "Potatoes",
      "Tropico",
    ],
  },
  {
    id: 11,
    name: "Cap d'Agde",
    description:
      "Le site du Cap d'Agde était un marais, séparé de la mer par de larges plages de sable, au milieu desquelles s'avançait le promontoire rocheux ayant donné son nom à la station. Seules quelques maisons bâties sur la côte étaient présentes. Dans les années 1960, le gouvernement décide de développer le tourisme dans le Languedoc-Roussillon avec le plan Racine. Une société d'économie mixte, la Société d’équipement du Biterrois et de son littoral (SEBLI) est chargée de développer la station. L'avant-port et l'île des Pêcheurs, la promenade sur les dalles de basalte et carreaux de céramique. Établies sur le marais en le creusant, les iles et marinas fournissent l'ensemble de l'attractivité de Cap-centre. Poste de vigie La Roquille, toilettes publiques et terrasses des restaurants, promenade amenant face au Village naturiste. Architecture du béton banché à refends apparents (ici à fruit) 1975. En 1967, les travaux de creusement du port de plaisance commencent. Quelques immeubles sont construits. De gigantesques parkings sur la zone portuaire sont créés, ils sont de forme circulaire typique ailleurs que sur le port et le grand boulevard dont ils séparent les deux voies. Ils représentent toujours aujourd'hui la quasi-totalité des places et ils fournissent les « points de repère » numérotés sur le plan de la ville le long de la côte.",
    pic1: capdagde,
    pic2: capdagde2,
    key: [
      "Naturiste",
      "Spa",
      "Hamac",
      "Aller au marché",
      "Whisky",
      "Lève tard",
      "Danser",
      "Repos",
      "Boeuf",
      "Nature",
      "Payer",
      "Potatoes",
      "Tropico",
    ],
  },
  {
    id: 12,
    name: "Reykjavik",
    description:
      "Reykjavik (en islandais littéralement « Baie-des-Fumées ») est la capitale de l'Islande. Elle se situe à environ 250 km au sud du cercle polaire arctique, ce qui en fait la capitale la plus septentrionale d'un État souverain (la capitale du Groenland, Nuuk, étant située quelques kilomètres plus au nord). Elle s'étale entre deux fjords, dans une zone comptant de nombreuses sources chaudes, le long d'une baie (vík en islandais). Elle est ainsi considérée comme la ville la « plus verte du monde » : on y compte environ 410 m² d'espaces verts par habitant. C'est la ville la plus peuplée du pays, avec environ 130 000 habitants. Avec l'agglomération, elle regroupe pratiquement les deux tiers de la population de l'île, soit environ 220 000 habitants. Son emplacement se situe à l'endroit même où s'installent en 874 les premiers colons conduits par Ingólfur Arnarson. Pourtant, le site n'est peuplé que de quelques centaines d'habitants en 1786 lorsqu'il est promu au rang de municipalité, avant de devenir le siège des institutions religieuses et politiques de l'île, à la faveur de la construction de l'État islandais. C'est à Reykjavik que sont concentrées les activités politiques, industrielles, commerciales, et culturelles du pays.",
    pic1: reykjavik,
    pic2: reykjavik2,
    key: [
      "Frais",
      "Montagne",
      "Randonnée",
      "Sunset",
      "Sport",
      "Whisky",
      "Lève tôt",
      "Paysage",
      "Aventure",
      "Poisson",
      "Nature",
      "Payer",
      "Nuit",
      "Expression",
    ],
  },
  {
    id: 13,
    name: "Marrakech",
    description:
      "Marrakech, est une ville située dans le centre du Maroc au pied des montagnes de l'Atlas. Marrakech est surnommée « la ville rouge » ou la « ville ocre » en référence à la couleur rouge d'une grande partie de ses immeubles et ses maisons. Marrakech et son aire urbaine comptent en 2020 un peu plus d'un million d'habitants. Par sa population, la ville est la troisième agglomération du pays, à égalité avec sa rivale historique, Fès, et derrière Casablanca et Rabat. Cité impériale, au même titre que Meknès, Fès et Rabat, Marrakech fut la capitale du Maroc pendant près de 350 ans, sous les dynasties Almoravide (XIe–XIIe siècles), Almohade (XIIe–XIIIe siècles), Saâdienne (XVIe–XVIIe siècles), ainsi que sous le règne de Mohammed ben Abdallah de l'actuelle dynastie alaouite (régnant de 1757 à 1790). Marrakech abrite une vaste médina de 600 hectares, la plus peuplée d'Afrique du nord, et classée au patrimoine mondial de l'humanité par l'UNESCO. Grâce à la vitalité de sa médina, vieille de 900 ans, ses infrastructures hôtelières de classe mondiale et son climat ensoleillé, Marrakech s'est imposée comme la capitale incontestée du tourisme au Maroc. Desservie par le deuxième aéroport du pays en termes de trafic, l'aéroport Marrakech - Ménara, la ville a accueilli en 2019 près de 3 millions de visiteurs.",
    pic1: marrakech,
    pic2: marrakech2,
    key: [
      "Thé",
      "Farniente",
      "PMU",
      "Spa",
      "Hamac",
      "Aller au marché",
      "Lève tard",
      "Danser",
      "Paysage",
      "Boeuf",
      "Négocier",
      "Oppression",
      "Potatoes",
      "Tropico",
    ],
  },
];

export default Destinations;
