const DbQuestion = [
  {
    id: 1,
    question: "Thé ou Café ?",
    response1: "Thé",
    response2: "Café",
  },
  {
    id: 2,
    question: "Sucré ou Salé ?",
    response1: "Sucré",
    response2: "Salé",
  },
  {
    id: 3,
    question: "Voiture ou Transport en commun ?",
    response1: "Voiture",
    response2: "Transport en commun",
  },
  {
    id: 4,
    question: "Maillot de bain ou Naturiste ?",
    response1: "Maillot de bain",
    response2: "Naturiste",
  },
  {
    id: 5,
    question: "Frais ou Farniente ?",
    response1: "Frais",
    response2: "Farnienete",
  },
  {
    id: 6,
    question: "Burger ou Pizza ?",
    response1: "Burger",
    response2: "Pizza",
  },
  {
    id: 7,
    question: "Plage ou Montagne ?",
    response1: "Plage",
    response2: "Montagne",
  },
  {
    id: 8,
    question: "Vin ou Bière ?",
    response1: "Vin",
    response2: "Bière",
  },
  {
    id: 9,
    question: "PMU ou Etoilé ?",
    response1: "PMU",
    response2: "Etoilé",
  },
  {
    id: 10,
    question: "Randonnée ou Musée ?",
    response1: "Randonnée",
    response2: "Musée",
  },
  {
    id: 11,
    question: "Sunset ou Sunrise ?",
    response1: "Sunset",
    response2: "Sunrise",
  },
  {
    id: 12,
    question: "Spa ou SPA?",
    response1: "Spa",
    response2: "SPA",
  },
  {
    id: 13,
    question: "Sport extrême ou Hamac ?",
    response1: "Sport extrême",
    response2: "Hamac",
  },
  {
    id: 14,
    question: "Marcher ou Aller au marché ?",
    response1: "Marcher",
    response2: "Aller au marché",
  },
  {
    id: 15,
    question: "Rhum ou Whisky ?",
    response1: "Rhum",
    response2: "Whisky",
  },
  {
    id: 16,
    question: "Lève tôt ou Lève tard ?",
    response1: "Lève tôt",
    response2: "Lève tard",
  },
  {
    id: 17,
    question: "Danser toute la nuit ou Se coucher tôt ?",
    response1: "Danser toute la nuit",
    response2: "Se coucher tôt",
  },
  {
    id: 18,
    question: "Paysages Ou Immeubles?",
    response1: "Paysages",
    response2: "Immeubles",
  },
  {
    id: 19,
    question: "Aventure ou Repos ?",
    response1: "Aventure",
    response2: "Repos",
  },
  {
    id: 20,
    question: "Désert ou Forêt tropicale ?",
    response1: "Désert",
    response2: "Forêt tropicale",
  },
  {
    id: 21,
    question: "Flûte de pan ou Guitare ?",
    response1: "Flûte de pan",
    response2: "Guitare",
  },
  {
    id: 22,
    question: "Boeuf ou Poisson ?",
    response1: "Boeuf",
    response2: "Poisson",
  },
  {
    id: 23,
    question: "Nature ou Peinture ?",
    response1: "Nature",
    response2: "Peinture",
  },
  {
    id: 24,
    question: "Fromage ou Chocolat ?",
    response1: "Fromage",
    response2: "Chocolat",
  },
  {
    id: 25,
    question: "Négocier ou Payer plein pot ?",
    response1: "Négocier",
    response2: "Payer plein pot",
  },
  {
    id: 26,
    question: "Calme ou Tempête ?",
    response1: "Calme",
    response2: "Tempête",
  },
  {
    id: 27,
    question: "Jour ou Nuit ?",
    response1: "Jour",
    response2: "Nuit",
  },
  {
    id: 28,
    question: "Expression ou Oppression ?",
    response1: "Expression",
    response2: "Oppression",
  },
  {
    id: 29,
    question: "Potatoes ou Frites ?",
    response1: "Potatoes",
    response2: "Frites",
  },
  {
    id: 30,
    question: "Tropique ou Tropico ?",
    response1: "Tropique",
    response2: "Tropico",
  },
];
